version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls -la"

workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-project-setup # only deploy on the circleci-project-setup branch
