name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD_MDT }}
          port: 22
          script: |
            cd /usr/app/nextjs-github-actions
            git pull origin main
            git status
            npm install --only=prod
            npm run build
            pm2 restart nextjs-github-actions
