name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /usr/app/nextjs-github-actions
            git pull origin main
            git status
            npm install --only=prod
            npm run build

            # Check if the app is running with pm2
            if pm2 show nextjs-github-actions > /dev/null 2>&1; then
              # App is running, restart it
              pm2 restart nextjs-github-actions
            else
              # App is not running, start it
              pm2 start npm --name "nextjs-github-actions" -- start
            fi
